set-option -g prefix C-a
bind-key C-a last-window
bind-key a send-prefix
set -g status-style bg=#263238,fg=#80cbc4
set -g base-index 1
set -g mouse on
set -s escape-time 0
<<<<<<< Updated upstream
set-option -g renumber-windows on
set-window-option -g window-status-format '#I:#{b:pane_current_path}'
set-window-option -g window-status-current-format '#[fg=orange,bold]#I:#{b:pane_current_path}*#[default]'

set -g @plugin 'sainnhe/tmux-fzf'

||||||| Stash base
setw -g aggresive-resize on
=======
setw -g aggresive-resize on
set -g mouse on


>>>>>>> Stashed changes
