set-option -g prefix C-a
bind-key C-a last-window
bind-key a send-prefix
set -g base-index 1
set -s escape-time 0
set -g mouse on
set-option -g renumber-windows on
set-window-option -g window-status-format '#I:#{b:pane_current_path}'
set-window-option -g window-status-current-format '#[fg=green,bold]#I:#{b:pane_current_path}*#[default]'
