[editor]
line-number = "relative"

[keys.normal]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"]
